Add offline mode to the quark script

diff --git a/bin/quark b/bin/quark
--- a/bin/quark
+++ b/bin/quark
@@ -1,32 +1,31 @@
 #!/bin/bash
 
-# Created by argbash-init v2.7.1
-# Rearrange the order of options below according to what you would like to see in the help message.
-# ARG_OPTIONAL_SINGLE([groupId],[g],[groupId of the generated project],[io.xstefank])
-# ARG_OPTIONAL_SINGLE([version],[v],[version of the generated project],[1.0-SNAPSHOT])
+# Created by argbash-init v2.10.0
+# ARG_OPTIONAL_SINGLE([groupId],[g],[gropuId of the generated project],[io.xstefank])
+# ARG_OPTIONAL_SINGLE([version],[v],[version of the generated project],[999-SNAPSHOT])
+# ARG_OPTIONAL_BOOLEAN([offline],[o],[work offline],[off])
 # ARG_POSITIONAL_SINGLE([artifactId],[artifactId of the generated project])
 # ARG_DEFAULTS_POS()
 # ARG_HELP([<The general help message of my script>])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.7.1 one line above ###
+### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
 
 die()
 {
-	local _ret=$2
-	test -n "$_ret" || _ret=1
-	test "$_PRINT_HELP" = yes && print_help >&2
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	echo "$1" >&2
-	exit ${_ret}
+	exit "${_ret}"
 }
 
 
 begins_with_short_option()
 {
-	local first_option all_short_options='gvh'
+	local first_option all_short_options='gvoh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -36,16 +35,18 @@ _positionals=()
 _arg_artifactid=
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_groupid="io.xstefank"
-_arg_version="0.0.1"
+_arg_version="999-SNAPSHOT"
+_arg_offline="off"
 
 
 print_help()
 {
 	printf '%s\n' "<The general help message of my script>"
-	printf 'Usage: %s [-g|--groupId <arg>] [-v|--version <arg>] [-h|--help] <artifactId>\n' "$0"
+	printf 'Usage: %s [-g|--groupId <arg>] [-v|--version <arg>] [-o|--(no-)offline] [-h|--help] <artifactId>\n' "$0"
 	printf '\t%s\n' "<artifactId>: artifactId of the generated project"
-	printf '\t%s\n' "-g, --groupId: groupId of the generated project (default: 'io.xstefank')"
-	printf '\t%s\n' "-v, --version: version of the generated project (default: '0.0.1')"
+	printf '\t%s\n' "-g, --groupId: gropuId of the generated project (default: 'io.xstefank')"
+	printf '\t%s\n' "-v, --version: version of the generated project (default: '999-SNAPSHOT')"
+	printf '\t%s\n' "-o, --offline, --no-offline: work offline (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 }
 
@@ -78,6 +79,18 @@ parse_commandline()
 				;;
 			-v*)
 				_arg_version="${_key##-v}"
+				;;
+			-o|--no-offline|--offline)
+				_arg_offline="on"
+				test "${1:0:5}" = "--no-" && _arg_offline="off"
+				;;
+			-o*)
+				_arg_offline="on"
+				_next="${_key##-o}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-o" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
 				;;
 			-h|--help)
 				print_help
@@ -129,16 +142,27 @@ assign_positional_args 1 "${_positionals[@]}"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
+
+# vvv  PLACE YOUR CODE HERE  vvv
+
 QUARKUS_VERSION=2.4.2.Final
+
+if [ "$_arg_offline" == "on" ]; then
+  ADDITIONAL_PARAMS="$ADDITIONAL_PARAMS -DquarkusRegistryClient=false"
+fi
 
 mvn io.quarkus:quarkus-maven-plugin:$QUARKUS_VERSION:create \
     -DprojectGroupId=$_arg_groupid \
     -DprojectArtifactId=$_arg_artifactid \
     -DprojectVersion=$_arg_version \
     -DclassName="io.xstefank.PingResource" \
+    $ADDITIONAL_PARAMS \
     -Dpath="/ping"
 #    -Dquarkus.platform.artifact-id=quarkus-bom \
 #    -Dquarkus.platform.version=$QUARKUS_VERSION \
 #    -Dquarkus-plugin.version=$QUARKUS_VERSION
+
+
+# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^
 
 # ] <-- needed because of Argbash
