Add interval option to repeat-command

diff --git a/bin/repeat-command b/bin/repeat-command
--- a/bin/repeat-command
+++ b/bin/repeat-command
@@ -1,5 +1,120 @@
 #!/bin/bash
 
+# Created by argbash-init v2.8.1
+# Rearrange the order of options below according to what you would like to see in the help message.
+# ARG_OPTIONAL_SINGLE([interval],[n],[The repetition interval],[0.1])
+# ARG_POSITIONAL_SINGLE([command],[The command to be repeated])
+# ARG_DEFAULTS_POS()
+# ARG_HELP([<The general help message of my script>])
+# ARGBASH_GO()
+# needed because of Argbash --> m4_ignore([
+### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+
+
+die()
+{
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
+	echo "$1" >&2
+	exit "${_ret}"
+}
+
+
+begins_with_short_option()
+{
+	local first_option all_short_options='nh'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+# THE DEFAULTS INITIALIZATION - POSITIONALS
+_positionals=()
+_arg_command=
+# THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_interval="0.1"
+
+
+print_help()
+{
+	printf '%s\n' "<The general help message of my script>"
+	printf 'Usage: %s [-n|--interval <arg>] [-h|--help] <command>\n' "$0"
+	printf '\t%s\n' "<command>: The command to be repeated"
+	printf '\t%s\n' "-n, --interval: The repetition interval (default: '0.1')"
+	printf '\t%s\n' "-h, --help: Prints help"
+}
+
+
+parse_commandline()
+{
+	_positionals_count=0
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-n|--interval)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_interval="$2"
+				shift
+				;;
+			--interval=*)
+				_arg_interval="${_key##--interval=}"
+				;;
+			-n*)
+				_arg_interval="${_key##-n}"
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_last_positional="$1"
+				_positionals+=("$_last_positional")
+				_positionals_count=$((_positionals_count + 1))
+				;;
+		esac
+		shift
+	done
+}
+
+
+handle_passed_args_count()
+{
+	local _required_args_string="'command'"
+	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+}
+
+
+assign_positional_args()
+{
+	local _positional_name _shift_for=$1
+	_positional_names="_arg_command "
+
+	shift "$_shift_for"
+	for _positional_name in ${_positional_names}
+	do
+		test $# -gt 0 || break
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		shift
+	done
+}
+
+parse_commandline "$@"
+handle_passed_args_count
+assign_positional_args 1 "${_positionals[@]}"
+
+# OTHER STUFF GENERATED BY Argbash
+
+### END OF CODE GENERATED BY Argbash (sortof) ### ])
+# [ <-- needed because of Argbash
+
+
 cleanup ()
 {
 kill -s SIGTERM $!
@@ -8,5 +123,8 @@ exit 0
 
 trap cleanup SIGINT SIGTERM
 
-while sleep .1; do $1 & wait $!; done
+$_arg_command
 
+while sleep $_arg_interval; do $_arg_command & wait $!; done
+
+# ] <-- needed because of Argbash
