Refactor build2 script

diff --git a/wildfly/build2 b/wildfly/build2
--- a/wildfly/build2
+++ b/wildfly/build2
@@ -70,29 +70,22 @@ assign_positional_args
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
+build_project() {
+  echo "building $1..."
+  cd $1
 
-cd $_arg_project1_dir
-echo "building $PWD..."
+  mvn clean install -DskipTests -Dcheckstyle.skip -Dmaven.javadoc.skip -Denforcer.skip
 
-mvn clean install -DskipTests -Dcheckstyle.skip -Dmaven.javadoc.skip -Denforcer.skip
-
-if [ $? -eq 0 ]; then
-    echo "$PWD build successful"
-else
-    echo "$PWD build failed"
+  if [ $? -eq 0 ]; then
+    echo "$1 build successful"
+  else
+    echo "$1 build failed"
     exit
-fi
+  fi
+}
 
-cd $_arg_project2_dir
-echo "building $PWD..."
+build_project $_arg_project1_dir
 
-mvn clean install -DskipTests -Dcheckstyle.skip -Dmaven.javadoc.skip -Denforcer.skip
-
-if [ $? -eq 0 ]; then
-    echo "$PWD build successful"
-else
-    echo "$PWD build failed"
-    exit
-fi
+build_project $_arg_project2_dir
 
 # ] <-- needed because of Argbash
